---
kind: Service
apiVersion: v1
metadata:
  name: {{app_name}}
spec:
  selector:
    app: {{app_name}}
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: {{app_name}}
